### ISSUE TITLE
Time elapsed is displayed incorrectly

### ISSUE THREAD

**Issue by eskettit** [Motschen/Retroblur#1]
![image](https://user-images.githubusercontent.com/49410302/134438012-310881c5-fe1b-46ff-86af-1046d3f9aada.png)
![image](https://user-images.githubusercontent.com/49410302/134438271-5d8fb704-801c-427a-a201-d8a7831228ab.png)

Music elapsed time is displayed incorrectly.

OS: Windows 10
Spotify version = 1.1.68.632.g2b11de83
Spicetify version= 2.6.4

**Comment by Motschen** [comment]
It's likely fixed in the latest version, if it isn't, feel free to reopen.
