### ISSUE TITLE
Overlapping Volume Percentage

### ISSUE THREAD

**Issue by OnlYKai** [Motschen/Retroblur#11]
Volume Percentage by daksh2k:
![image](https://user-images.githubusercontent.com/67548894/198185989-45b33eaf-9553-4f95-85b8-e19aa67e82a9.png)

Volume percentage and edit by jerontvb:
![image](https://user-images.githubusercontent.com/67548894/198186256-49fc3eee-05bd-4321-8eee-acb4cee57f65.png)

**Comment by EggyEMOD** [comment]
hi, i am having the same issue but i want to change the background color and dont know how.

**Comment by Motschen** [comment]
Fixed in the latest version.
