### ISSUE TITLE
Wallpaper not working

### ISSUE THREAD

**Issue by man8000** [Motschen/Retroblur#17]
are there any solutions to fix the wallpaper also if i have to edit the theme without installing it from the market place how do i do that without the file .spicetify

**Comment by Motschen** [comment]
Now it should work again. There is a new item in the profile menu called wallpaper changer, where you can even change the wallpaper.

**Comment by man8000** [comment]
yeah the "edit wallpaper" option dose not work i would use a url or a picture i downloaded and nothing happens when i press save

**Comment by Motschen** [comment]
Are you using the latest version of the theme?
If you installed the theme via marketplace, you need to wait around 24 hours for the update to be recognized.

**Comment by man8000** [comment]
yeah i installed it via marketplace ill wait for it to do its thing

**Comment by DlbS02** [comment]
same issue here been more than 24hrs since the update

**Comment by DlbS02** [comment]
found a fix jus turn "Match wallpaper to the colour scheme" off and the custom wallpaper loads

**Comment by icantcode17** [comment]
i am completely lost on how to add my own custom wallpaper. i have spent the last 2 hours trying to find out how, and have not yet. please help. (if you would like to contact through discord my username is 108ior)

**Comment by Motschen** [comment]
> i am completely lost on how to add my own custom wallpaper. i have spent the last 2 hours trying to find out how, and have not yet. please help. (if you would like to contact through discord my username is 108ior)

Click on your profile picture in Spotify and select "Change Wallpaper", set the toggle to off and then select the desired picture.

**Comment by icantcode17** [comment]
thank you!
