### ISSUE TITLE
Album artwork issue

### ISSUE THREAD

**Issue by DlbS02** [Motschen/Retroblur#18]
After the new spicetify update the album cover moved to the right anyone kno how to fix it
![image](https://github.com/Motschen/Retroblur/assets/135263859/f5359ea9-0588-4083-91db-71abfb15f16d)

**Comment by Motschen** [comment]
This is intended, as the left side now just doesn't provide enough space to house the cover.
If you don't like this change, you can manually edit the user.css file and remove the relevant lines.

**Comment by DlbS02** [comment]
Idk how to edit the user.css file or where to locate it and I also installed via marketplace
