### ISSUE TITLE
Right-click breaks the page

### ISSUE THREAD

**Issue by beuh0623** [Motschen/Retroblur#27]
Trying to edit anything will make me reload the page and for aspects to go wrong. 

![image](https://github.com/Motschen/Retroblur/assets/151049599/09524f7d-ce0d-40e7-ae8f-0d73459c377a)
![image](https://github.com/Motschen/Retroblur/assets/151049599/6e09e337-f086-4450-8545-49b4cad368b5)
_before and after right clicking on a playlist_

![image](https://github.com/Motschen/Retroblur/assets/151049599/b9c5bfe1-0fe9-4e1a-b049-19f70508d46e)
![image](https://github.com/Motschen/Retroblur/assets/151049599/81cb2693-59a3-40a2-a453-0a149b452ed0)
_before and after right clicking on a song in a playlist_

Anything I can do to fix this?

**Comment by Mami8** [comment]
Exactly the same here. Took some time to notice for me. Probably caused by the JavaScript file, what else could it be?

**Comment by Motschen** [comment]
I don't think it is caused by the JavaScript file. 
Spotify is weird, so sometimes the CSS can cause glitches. I'll investigate this further after my exams.

**Comment by Motschen** [comment]
Fixed, it was indeed caused by the JavaScript, my bad.
