### ISSUE TITLE
Bottom bar layout broken 

### ISSUE THREAD

**Issue by junkypurr** [Motschen/Retroblur#3]
A few problems I'm experiencing isn't with the background or anything like that, its the bar at the bottom. The pause button is seemingly broken and the song duration is behind a few buttons. The one other issue, that isn't really major for me is that the "Home" button collides with Spotify's little menu button in the top left corner. Any known fix for this?

**Comment by Chaxiraxi** [comment]
For the "Home" button colliding with Spotify's little dots at the top, you just need to add a margin at the top of the Nav-Bar menu. To do this, just add to the theme this little few lines of codes :
```css
.main-navBar-entryPoints {
  margin-top: 20px;
}
```
I made a Pull Request to patch this in the main branch (PR #10)
However, I don't have such an issue with your broken pause button, so I can't really help you, sorry.

**Comment by Motschen** [comment]
The collision with the three dots button is now fixed by only reducing the margin on linux desktops.
The duration text was also moved a few pixels to the left, so the overlap also shouldn't happen anymore.
Does the pause button issue still occur on the latest version, @junkypurr ?

**Comment by Motschen** [comment]
Closing this now; feel free to reopen if your issue still occurs.
