### ISSUE TITLE
Broken with the latest spotify version (home screen)

### ISSUE THREAD

**Issue by RaspberryKitty1** [Motschen/Retroblur#4]
Spotify for Windows
1.1.83.956.gbe7ea9a7
spicetify v2.9.7  

seems to only be somewhat broken on the home screen
![image](https://user-images.githubusercontent.com/28585042/165181623-0dc868d2-f331-484f-98f9-b4cc61756664.png)

**Comment by Motschen** [comment]
Sadly, I can't really continue development on this theme, since Spotify moved to a React backend and removed the Chrome Dev Tools.
There is a workaround, but it only works on Windows, but I'm definetely never gonna touch that OS again.

**Comment by Motschen** [comment]
Oh, wait, they actually fixed DevTools
