### ISSUE TITLE
WHEN ON PLAYLIST BACKGROUND IS MENT TO BE A BLURED BACKROUND BUT INSTEAD IS JUST PURPLE

### ISSUE THREAD

**Issue by CMMANGO** [Motschen/Retroblur#7]
When on a playlist in the past the backround behind all song names used to be a kind of blured version of the themes image but in stead its a solid purple color and isnt verry nice to look at tbh
![THEME ISSUE](https://user-images.githubusercontent.com/71497671/182776236-b451a69e-f724-49a6-9b91-e6ba795edb16.JPG)

**Comment by Motschen** [comment]
Did you install the theme via spicetify-marketplace?

**Comment by CMMANGO** [comment]
> Did you install the theme via spicetify-marketplace?

Yes through Spicetify market place I installed it and I had no problems in the past with it until recent

**Comment by Motschen** [comment]
Yeah, marketpace updates sometimes break the theme, I'll fix it soon, install the theme the normal way in the meantime.

**Comment by tetenc555** [comment]
I did that and it continued the same, I even switched to green and the color continued. Am I missing something in the config? First I installed via marketplace and now I switched to traditional metho
![Captura de Tela 2022-08-16 às 16 45 11](https://user-images.githubusercontent.com/66535690/184971314-133e5ee7-9004-48ba-926d-0586e669b8d7.png)
![Captura de Tela 2022-08-16 às 16 44 26](https://user-images.githubusercontent.com/66535690/184971430-f82e8d40-b30b-4d35-b0f9-4beabff6b3cb.png)
d

**Comment by Motschen** [comment]
Have you uninstalled the theme in spicetify-marketplace?

**Comment by tetenc555** [comment]
Yes, I uninstalled it, if not the color wouldn't even change it.

**Comment by diddyiddy** [comment]
I went into the user file and changed this:
![image](https://user-images.githubusercontent.com/113214333/189478346-027285d4-9526-465f-81fb-dc20adea367e.png)
to this:
![image](https://user-images.githubusercontent.com/113214333/189478355-5a9f28cd-d97c-4f38-b350-8ccf770727df.png)
and it seems to have fixed it.  I'm unsure of the ramifications to this outside of fixing the issue but its worked. Hope this helps.

**Comment by Motschen** [comment]
Fixed by merging #9 (Thanks again, Chaxiraxi)
